on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]

name: Handle Golang Build, Test and Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build linux amd64
      run: go build -v CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-X 'pihole_exporter/config.PackageName=pihole_exporter' -X 'pihole_exporter/config.Version=${{  github.ref_name }}'" -o release/linux/amd64/pihole_exporter-linux-amd64 .
    
    - name: Build linux arm64
      run: go build -v CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags="-X 'pihole_exporter/config.PackageName=pihole_exporter' -X 'pihole_exporter/config.Version=${{  github.ref_name }}'" -o release/linux/arm64/pihole_exporter-linux-arm64 .
    
    - name: Build linux arm
      run: go build -v CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -ldflags="-X 'pihole_exporter/config.PackageName=pihole_exporter' -X 'pihole_exporter/config.Version=${{  github.ref_name }}'" -o release/linux/arm/pihole_exporter-linux-arm .
    
    - name: Build windows amd64
      run: go build -v CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-X 'pihole_exporter/config.PackageName=pihole_exporter' -X 'pihole_exporter/config.Version=${{  github.ref_name }}'" -o release/windows/amd64/pihole_exporter-windows-amd64 .
    
    - name: Build darwin amd64
      run: go build -v CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-X 'pihole_exporter/config.PackageName=pihole_exporter' -X 'pihole_exporter/config.Version=${{  github.ref_name }}'" -o release/darwin/amd64/pihole_exporter-darwin-amd64 .
    
    - name: Build darwin arm64
      run: go build -v CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags="-X 'pihole_exporter/config.PackageName=pihole_exporter' -X 'pihole_exporter/config.Version=${{  github.ref_name }}'" -o release/darwin/arm64/pihole_exporter-darwin-arm64 .

    - name: Test
      run: go test -v ./...
    
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          release/linux/amd64/pihole_exporter-linux-amd64
          release/linux/arm64/pihole_exporter-linux-arm64
          release/linux/arm/pihole_exporter-linux-arm
          release/windows/amd64/pihole_exporter-windows-amd64
          release/darwin/amd64/pihole_exporter-darwin-amd64
          release/darwin/arm64/pihole_exporter-darwin-arm64
